AWSTemplateFormatVersion: 2010-09-09
Description: Angel tree dynamodb donation table stream trigger email to admins
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs12.x
    MemorySize: 128
    Timeout: 5

Resources:
  processDynamoDBDonationStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 192
      Handler: index.donationStreamEmailAdmins
      Description: New donation item triggers SNS email to admins
      Policies:
        - AWSLambdaDynamoDBExecutionRole
        - DynamoDBReadPolicy:
            TableName: Child
        - SNSPublishMessagePolicy:
            TopicName: Donations
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: arn:aws:dynamodb:us-west-1:486040421677:table/Donation/stream/2020-11-30T12:18:18.646
            BatchSize: 1
            StartingPosition: LATEST
            Enabled: true
      EventInvokeConfig:
        MaximumRetryAttempts: 2
