version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "angel-tree-donation-stream-email-donors"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-eqph7jq284wt"
s3_prefix = "angel-tree-donation-stream-email-donors"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
