AWSTemplateFormatVersion: 2010-09-09
Description: Angel Tree Tables
Transform:
  - AWS::Serverless-2016-10-31

Resources:
  SummaryTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      TableName: Summary
      AttributeDefinitions:
        - AttributeName: use
          AttributeType: S
      KeySchema:
        - AttributeName: use
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 2
  ChildTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      TableName: Child
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 1
  DonationTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      TableName: Donation
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 2
  WaitlistTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      TableName: Waitlist
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  ChildTableStreamArn:
    Value: !GetAtt ChildTable.StreamArn
    Export:
      Name: AngelTree-ChildTableStreamArn
  DonationTableStreamArn:
    Value: !GetAtt DonationTable.StreamArn
    Export:
      Name: AngelTree-DonationTableStreamArn
  WaitlistTableStreamArn:
    Value: !GetAtt WaitlistTable.StreamArn
    Export:
      Name: AngelTree-WaitlistTableStreamArn
