AWSTemplateFormatVersion: 2010-09-09
Description: Angel tree dynamodb donation table stream trigger email to donors
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs12.x
    MemorySize: 128
    Timeout: 5

Resources:
  processDynamoDBDonationStreamEmailDonorsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.donationStreamEmailDonors
      Description: New donation item triggers SendGrid email to the donor
      Policies:
        - AWSLambdaDynamoDBExecutionRole
        - DynamoDBReadPolicy:
            TableName: Child
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !ImportValue AngelTree-DonationTableStreamArn
            BatchSize: 1
            StartingPosition: LATEST
            Enabled: true
      EventInvokeConfig:
        MaximumRetryAttempts: 2
