version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "angel-tree-donation-stream-email-admins"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
