AWSTemplateFormatVersion: 2010-09-09
Description: Angel tree dynamodb donation table stream trigger email to admins
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs12.x
    MemorySize: 128
    Timeout: 5

Parameters:
  FirstSubscriber:
    Type: String
    Default: someone@somewhere.com

Resources:
  DonationEmailAdmins:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Angel Tree Donation Email Admins
      Subscription:
        - Endpoint: !Ref FirstSubscriber
          Protocol: email
  ProcessDynamoDBDonationStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 192
      Handler: index.donationStreamEmailAdmins
      Description: New donation item triggers SNS email to admins
      Environment:
        Variables:
          DONATION_TOPIC_ARN: !Ref DonationEmailAdmins
      Policies:
        - AWSLambdaDynamoDBExecutionRole
        - DynamoDBReadPolicy:
            TableName: Child
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt DonationEmailAdmins.TopicName

      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !ImportValue AngelTree-DonationTableStreamArn
            BatchSize: 1
            StartingPosition: LATEST
            Enabled: true
      EventInvokeConfig:
        MaximumRetryAttempts: 2
